site_name: The Bonvi LAB
site_url: https://il-bonvi.github.io/the-Bonvi-LAB/

theme:
  name: material
  language: it

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes

nav:
  - Home: index.md

  - Manuale ematologico:
      - Introduzione: Manuale ematologico\00_introduzione.md
      - Emocromo: Manuale ematologico\02_biomarcatori_emocromo.md
      - Ferro: Manuale ematologico\03_biomarcatori_ferro.md
      - Infiammazione e danno muscolare: Manuale ematologico\04_biomarcatori_infiammazione_danno_muscolare.md
      - Funzione dell'organo: Manuale ematologico\05_biomarcatori_funzione_organo.md
      - Micronutrienti ed elettroliti: Manuale ematologico\06_biomarcatori_micronutrienti_elettroliti.md
      - Metabolismo e ormoni: Manuale ematologico\07_biomarcatori_metabolico_ormonale.md
      - Altura: Manuale ematologico\08_altura.md
      - Monitoraggio stagionale: Manuale ematologico\09_monitoraggio_stagionale.md
      - Sport differenti: Manuale ematologico\10_sport_differenti.md
      - Algoritmi decisionali: Manuale ematologico\11_algoritmi_decisionali.md
      - Casi pratici emocromo/ferro: Manuale ematologico\12_casi_pratici_emocromo_ferro.md
      - Casi pratici infiammazione/muscolo/organo: Manuale ematologico\13_casi_pratici_infiammazione_muscolo_organo.md
      - Casi pratici altura/stagionale/sport: Manuale ematologico\14_casi_pratici_altura_stagionale_sport.md
